
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE
  namespace: default
  labels:
    app: $IMAGE
spec:
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: $IMAGE
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate    
  template:
    metadata:
      labels:
        app: $IMAGE
    spec:
      containers:
      - name: $IMAGE
        image: gcr.io/$GCP_PROJECT/$IMAGE:latest
        imagePullPolicy: Always
        # resources:
          # limits: 
            # memory: 64Mi
            # cpu: "250m"
          # requests:
            # memory: 32Mi
            # cpu: "200m"
        ports:
        - containerPort: 8082
# ---		
# apiVersion: "autoscaling/v2beta1"
# kind: "HorizontalPodAutoscaler"
# metadata:
  # namespace: "default"
  # minReplicas: 1
  # maxReplicas: 5
  # labels:
    # app: "$IMAGE"
  # metrics:
  # - type: "Resource"
    # resource:
      # name: "cpu"
      # targetAverageUtilization: 80
      

---
apiVersion: v1
kind: Service
metadata:
  name: $IMAGE
  annotations:
    networking.gke.io/load-balancer-type: External
  labels:
    app: $IMAGE
spec:
  type: LoadBalancer
  selector:
    app: $IMAGE
  ports:
  - port: 8080
    targetPort: 8082
    protocol: TCP

---
apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: autoscaler
    namespace: default
  spec:
    maxReplicas: 10
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: autoscaler
    targetCPUUtilizationPercentage: 80
kind: List
