on:
  push:
    branches:
    - main
       paths-ignore:
        - '*.md'
        - '.github/workflows/**'

  pull_request:
        branches:
        - main
       paths-ignore:
        - '*.md'
        - '.github/workflows/**'
        
        
jobs:

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan

    #   # On push to main, build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve

   pytest:
    # needs: pylint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest


  pylint:
    # needs: pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      run: |
        pylint --exit-zero $(ls -R | grep .py$ | xargs)

 #========================ADD build test HERE ===================================
 #========================AND MAY BE BANDIT ===================================

  pushtoDockerHub:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      # build docker image and push to docker hub
      # only if the app build and test successfully
      # needs: [build_test]

      steps:
        - name: checkout repo
          uses: actions/checkout@v2

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        # - name: Build and push
          # uses: docker/build-push-action@v2
          # with:
            # context: ./
            # file: ./Dockerfile
            # push: true
            # tags: ${{ secrets.DOCKERHUB_USERNAME }}/py-exam:latest
          
        # - name: Run the image in a container
          # uses: addnab/docker-run-action@v3
          # with:
            # image: ${{ secrets.DOCKERHUB_USERNAME }}/py-exam:latest
            # run: |
              # echo "runing the docker image"

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v3
          with:
            images: ${{ secrets.DOCKERHUB_USERNAME }}/py-exam:latest
      
        - name: Build and push Docker imagee
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
